project: 
  type: website

website:
  title: "Madison Ballard - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/mballard181/mballard181.github.io
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Madison Ballard 2024©"
    right: 
      - icon: linkedin
        href: www.linkedin.com/in/madison-ballard181

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Data Cleansing"
        file: cleansing.qmd
      - text: "Data Exploration"
        file: exploration.qmd
      - text: "Story Telling"
        file: story_telling.qmd
      - text: "Machine Learning"
        file: ml.qmd
      - text: "Full Stack"
        file: full_stack.qmd
      - text: "Competition"
        file: competition.qmd
  
  # learn more about navication here https://quarto.org/docs/websites/website-navigation.html
  # comment out any of the sections below to turn off the sidebar

  sidebar: 
    - title: "Data Cleansing"
      style: "docked"
      background: light
      contents:
        - text: "Data Cleansing"
          file: cleansing.qmd
        - text: "---"
        - text: "Project 1"
          file: Cleansing_Projects/P1_template.qmd
        - text: "---"
        - text: "Project 2"
          file: Cleansing_Projects/P2_template.qmd
        - text: "---"
        - text: "Project 3"
          file: Cleansing_Projects/P3_template.qmd
        - text: "---"
        - text: "Project 4"
          file: Cleansing_Projects/P4_template.qmd
        - text: "---"
        - text: "Project 5"
          file: Cleansing_Projects/P5_template.qmd
        - text: "---"
    - title: "Data Exploration"
      style: "docked"
      background: light
      contents:
        - text: "Data Exploration"
          file: exploration.qmd
        - text: "---"
        - text: "Project 1"
          file: Exploration_Projects/P1_template.qmd
        - text: "---"
        - text: "Project 2"
          file: Exploration_Projects/P2_template.qmd
        - text: "---"
        - text: "Project 3"
          file: Exploration_Projects/P3_template.qmd
        - text: "---"
        - text: "Project 4"
          file: Exploration_Projects/P4_template.qmd
        - text: "---"
        - text: "Project 5"
          file: Exploration_Projects/P5_template.qmd
        - text: "---"
    - title: "Story Telling"
      style: "docked"
      background: light
      contents:
        - text: "Story Telling"
          file: story_telling.qmd
        - text: "---"
        - text: "Project 1"
          file: Story_Telling/P1_template.qmd
        - text: "---"
        - text: "Project 2"
          file: Story_Telling/P2_template.qmd
        - text: "---"
        - text: "Project 3"
          file: Story_Telling/P3_template.qmd
        - text: "---"
        - text: "Project 4"
          file: Story_Telling/P4_template.qmd
        - text: "---"
        - text: "Project 5"
          file: Story_Telling/P5_template.qmd
        - text: "---"
    - title: "Machine Learning"
      style: "docked"
      background: light
      contents:
        - text: "Machine Learning"
          file: ml.qmd
        - text: "---"
        - text: "Project 1"
          file: Machine_Learning/P1_template.qmd
        - text: "---"
        - text: "Project 2"
          file: Machine_Learning/P2_template.qmd
        - text: "---"
        - text: "Project 3"
          file: Machine_Learning/P3_template.qmd
        - text: "---"
        - text: "Project 4"
          file: Machine_Learning/P4_template.qmd
        - text: "---"
        - text: "Project 5"
          file: Machine_Learning/P5_template.qmd
        - text: "---"
    - title: "Full Stack"
      style: "docked"
      background: light
      contents:
        - text: "Full Stack"
          file: full_stack.qmd
        - text: "---"
        - text: "Project 1"
          file: Full_Stack/P1_template.qmd
        - text: "---"
        - text: "Project 2"
          file: Full_Stack/P2_template.qmd
        - text: "---"
        - text: "Project 3"
          file: Full_Stack/P3_template.qmd
        - text: "---"
        - text: "Project 4"
          file: Full_Stack/P4_template.qmd
        - text: "---"
        - text: "Project 5"
          file: Full_Stack/P5_template.qmd
        - text: "---"
    - title: "Competition"
      style: "docked"
      background: light
      contents:
        - text: "Competition"
          file: competition.qmd
        - text: "---"
        - text: "Project 1"
          file: Competition/P1_template.qmd
        - text: "---"
        - text: "Project 2"
          file: Competition/P2_template.qmd
        - text: "---"
        - text: "Project 3"
          file: Competition/P3_template.qmd
        - text: "---"
        - text: "Project 4"
          file: Competition/P4_template.qmd
        - text: "---"
        - text: "Project 5"
          file: Competition/P5_template.qmd
        - text: "---"
  
format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



